DROP TABLE SECURITY_USER;
CREATE table SECURITY_USER (
    user_id SERIAL PRIMARY KEY ,
    username TEXT NOT NULL ,
    password TEXT NOT NULL ,
    role TEXT NOT NULL ,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
SELECT * FROM SECURITY_USER;